"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gps_t(object):
    __slots__ = ["time", "lat", "lon", "alt"]

    def __init__(self):
        self.time = ""
        self.lat = ""
        self.lon = ""
        self.alt = ""

    def encode(self):
        buf = BytesIO()
        buf.write(gps_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __time_encoded = self.time.encode('utf-8')
        buf.write(struct.pack('>I', len(__time_encoded)+1))
        buf.write(__time_encoded)
        buf.write(b"\0")
        __lat_encoded = self.lat.encode('utf-8')
        buf.write(struct.pack('>I', len(__lat_encoded)+1))
        buf.write(__lat_encoded)
        buf.write(b"\0")
        __lon_encoded = self.lon.encode('utf-8')
        buf.write(struct.pack('>I', len(__lon_encoded)+1))
        buf.write(__lon_encoded)
        buf.write(b"\0")
        __alt_encoded = self.alt.encode('utf-8')
        buf.write(struct.pack('>I', len(__alt_encoded)+1))
        buf.write(__alt_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps_t()
        __time_len = struct.unpack('>I', buf.read(4))[0]
        self.time = buf.read(__time_len)[:-1].decode('utf-8', 'replace')
        __lat_len = struct.unpack('>I', buf.read(4))[0]
        self.lat = buf.read(__lat_len)[:-1].decode('utf-8', 'replace')
        __lon_len = struct.unpack('>I', buf.read(4))[0]
        self.lon = buf.read(__lon_len)[:-1].decode('utf-8', 'replace')
        __alt_len = struct.unpack('>I', buf.read(4))[0]
        self.alt = buf.read(__alt_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps_t in parents: return 0
        tmphash = (0xc4956078afa20e60) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps_t._packed_fingerprint is None:
            gps_t._packed_fingerprint = struct.pack(">Q", gps_t._get_hash_recursive([]))
        return gps_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

