classdef ThrottleInfoReport < robotics.ros.Message
    %ThrottleInfoReport MATLAB implementation of dbw_mkz_msgs/ThrottleInfoReport
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dbw_mkz_msgs/ThrottleInfoReport' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8255d20d2bbc661ad39074024259c71a' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        ThrottlePc
        ThrottleRate
        EngineRpm
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'EngineRpm', 'Header', 'ThrottlePc', 'ThrottleRate'} % List of non-constant message properties
        ROSPropertyList = {'engine_rpm', 'header', 'throttle_pc', 'throttle_rate'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ThrottleInfoReport(msg)
            %ThrottleInfoReport Construct the message object ThrottleInfoReport
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ThrottleInfoReport', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function throttlepc = get.ThrottlePc(obj)
            %get.ThrottlePc Get the value for property ThrottlePc
            throttlepc = single(obj.JavaMessage.getThrottlePc);
        end
        
        function set.ThrottlePc(obj, throttlepc)
            %set.ThrottlePc Set the value for property ThrottlePc
            validateattributes(throttlepc, {'numeric'}, {'nonempty', 'scalar'}, 'ThrottleInfoReport', 'ThrottlePc');
            
            obj.JavaMessage.setThrottlePc(throttlepc);
        end
        
        function throttlerate = get.ThrottleRate(obj)
            %get.ThrottleRate Get the value for property ThrottleRate
            throttlerate = single(obj.JavaMessage.getThrottleRate);
        end
        
        function set.ThrottleRate(obj, throttlerate)
            %set.ThrottleRate Set the value for property ThrottleRate
            validateattributes(throttlerate, {'numeric'}, {'nonempty', 'scalar'}, 'ThrottleInfoReport', 'ThrottleRate');
            
            obj.JavaMessage.setThrottleRate(throttlerate);
        end
        
        function enginerpm = get.EngineRpm(obj)
            %get.EngineRpm Get the value for property EngineRpm
            enginerpm = single(obj.JavaMessage.getEngineRpm);
        end
        
        function set.EngineRpm(obj, enginerpm)
            %set.EngineRpm Set the value for property EngineRpm
            validateattributes(enginerpm, {'numeric'}, {'nonempty', 'scalar'}, 'ThrottleInfoReport', 'EngineRpm');
            
            obj.JavaMessage.setEngineRpm(enginerpm);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ThrottlePc = obj.ThrottlePc;
            cpObj.ThrottleRate = obj.ThrottleRate;
            cpObj.EngineRpm = obj.EngineRpm;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ThrottlePc = strObj.ThrottlePc;
            obj.ThrottleRate = strObj.ThrottleRate;
            obj.EngineRpm = strObj.EngineRpm;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ThrottlePc = obj.ThrottlePc;
            strObj.ThrottleRate = obj.ThrottleRate;
            strObj.EngineRpm = obj.EngineRpm;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dbw_mkz_msgs.ThrottleInfoReport.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dbw_mkz_msgs.ThrottleInfoReport;
            obj.reload(strObj);
        end
    end
end
