classdef TirePressureReport < robotics.ros.Message
    %TirePressureReport MATLAB implementation of dbw_mkz_msgs/TirePressureReport
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dbw_mkz_msgs/TirePressureReport' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'a2c91f746e5d8bec139c834f92ac7468' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        FrontLeft
        FrontRight
        RearLeft
        RearRight
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'FrontLeft', 'FrontRight', 'Header', 'RearLeft', 'RearRight'} % List of non-constant message properties
        ROSPropertyList = {'front_left', 'front_right', 'header', 'rear_left', 'rear_right'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = TirePressureReport(msg)
            %TirePressureReport Construct the message object TirePressureReport
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'TirePressureReport', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function frontleft = get.FrontLeft(obj)
            %get.FrontLeft Get the value for property FrontLeft
            frontleft = single(obj.JavaMessage.getFrontLeft);
        end
        
        function set.FrontLeft(obj, frontleft)
            %set.FrontLeft Set the value for property FrontLeft
            validateattributes(frontleft, {'numeric'}, {'nonempty', 'scalar'}, 'TirePressureReport', 'FrontLeft');
            
            obj.JavaMessage.setFrontLeft(frontleft);
        end
        
        function frontright = get.FrontRight(obj)
            %get.FrontRight Get the value for property FrontRight
            frontright = single(obj.JavaMessage.getFrontRight);
        end
        
        function set.FrontRight(obj, frontright)
            %set.FrontRight Set the value for property FrontRight
            validateattributes(frontright, {'numeric'}, {'nonempty', 'scalar'}, 'TirePressureReport', 'FrontRight');
            
            obj.JavaMessage.setFrontRight(frontright);
        end
        
        function rearleft = get.RearLeft(obj)
            %get.RearLeft Get the value for property RearLeft
            rearleft = single(obj.JavaMessage.getRearLeft);
        end
        
        function set.RearLeft(obj, rearleft)
            %set.RearLeft Set the value for property RearLeft
            validateattributes(rearleft, {'numeric'}, {'nonempty', 'scalar'}, 'TirePressureReport', 'RearLeft');
            
            obj.JavaMessage.setRearLeft(rearleft);
        end
        
        function rearright = get.RearRight(obj)
            %get.RearRight Get the value for property RearRight
            rearright = single(obj.JavaMessage.getRearRight);
        end
        
        function set.RearRight(obj, rearright)
            %set.RearRight Set the value for property RearRight
            validateattributes(rearright, {'numeric'}, {'nonempty', 'scalar'}, 'TirePressureReport', 'RearRight');
            
            obj.JavaMessage.setRearRight(rearright);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.FrontLeft = obj.FrontLeft;
            cpObj.FrontRight = obj.FrontRight;
            cpObj.RearLeft = obj.RearLeft;
            cpObj.RearRight = obj.RearRight;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.FrontLeft = strObj.FrontLeft;
            obj.FrontRight = strObj.FrontRight;
            obj.RearLeft = strObj.RearLeft;
            obj.RearRight = strObj.RearRight;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.FrontLeft = obj.FrontLeft;
            strObj.FrontRight = obj.FrontRight;
            strObj.RearLeft = obj.RearLeft;
            strObj.RearRight = obj.RearRight;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dbw_mkz_msgs.TirePressureReport.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dbw_mkz_msgs.TirePressureReport;
            obj.reload(strObj);
        end
    end
end
