classdef WatchdogCounter < robotics.ros.Message
    %WatchdogCounter MATLAB implementation of dbw_mkz_msgs/WatchdogCounter
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dbw_mkz_msgs/WatchdogCounter' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '49446aafd000e473e340dfb1d38eeb50' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        NONE = uint8(0)
        OTHERBRAKE = uint8(1)
        OTHERTHROTTLE = uint8(2)
        OTHERSTEERING = uint8(3)
        BRAKECOUNTER = uint8(4)
        BRAKEDISABLED = uint8(5)
        BRAKECOMMAND = uint8(6)
        BRAKEREPORT = uint8(7)
        THROTTLECOUNTER = uint8(8)
        THROTTLEDISABLED = uint8(9)
        THROTTLECOMMAND = uint8(10)
        THROTTLEREPORT = uint8(11)
        STEERINGCOUNTER = uint8(12)
        STEERINGDISABLED = uint8(13)
        STEERINGCOMMAND = uint8(14)
        STEERINGREPORT = uint8(15)
    end
    
    properties (Dependent)
        Source
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Source'} % List of non-constant message properties
        ROSPropertyList = {'source'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = WatchdogCounter(msg)
            %WatchdogCounter Construct the message object WatchdogCounter
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function source = get.Source(obj)
            %get.Source Get the value for property Source
            source = typecast(int8(obj.JavaMessage.getSource), 'uint8');
        end
        
        function set.Source(obj, source)
            %set.Source Set the value for property Source
            validateattributes(source, {'numeric'}, {'nonempty', 'scalar'}, 'WatchdogCounter', 'Source');
            
            obj.JavaMessage.setSource(source);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Source = obj.Source;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Source = strObj.Source;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Source = obj.Source;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dbw_mkz_msgs.WatchdogCounter.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dbw_mkz_msgs.WatchdogCounter;
            obj.reload(strObj);
        end
    end
end
